### PR TITLE
Use flex instead of width, Now Place doms get only necessary width

### PR DESCRIPTION
**Pull request by JafarAkhondali**
Hi,
Thank you for this library, It's very useful and helping me a lot.
I've changed sass file to use flex([It's now widely supported](http://caniuse.com/#feat=flexbox)) instead of width.

Before:
screenshot_20171004_054003

After(the screenshot is in Persian):
screenshot_20171004_053329

I'm only experienced with webpack and since you are using gulp i wasn't able to find what to do for PR and rest of files. I wanna do some more contributions like supporting RTL and [fixing this issue](https://github.com/Grible/timetable.js/issues/23), But need a guide for gulp.
Last commit on this repository is on one year ago, If i don't get any responses in a week i'll continue contribution in my fork.
Thanks.

### CODE REVIEW

**Comment by stevenaanen** [comment]
Hi Jafar, thanks for the contribution. You're totally right that flexbox can be used now that it is widely supported. It would be great to give this project a nice update using that and other refinements.

Concerning your pull request: what happens when there are headings which are very long? I didn't test but given the code i can imagine it would become larger so there wouldn't be any space left for the timetable itself if that happens.

Concerning gulp/the project setup it should be pretty easy. If you install gulp locally on your machine you should be able to use `gulp` for building, and `gulp serve` for watching in dev mode with automatic refresh. For the tests you can simply open the `test/index.html` file.

**Comment by JafarAkhondali** [comment]
Hi, Yes if the title is too long there will be no space left for time table. I think we can:

1. Set max-width for titles, Show overflow as three dots
2. Set max-width for titles, Let height the increase(it'll cause problems since events are using absolute height)
3. Set max-width + scrollX
4. Use something like [this](http://jquery-textfill.github.io/) to scale text in area
5. Use js to trim some of the title text

Which one seems better to you? IMO first option is better. Tell me your opinion and i'll work on it.
By the way i think we need a react version of this repository instead of vanilla? I'm still a newbie in react, maybe later i could implement it in react.

**Comment by stevenaanen** [comment]
I'd say option 1 is fine indeed: maybe a percentage max-width and an ellipsis if it's too large.

Great that you can work on it! Concerning React, it might be an idea to have a wrapper for React at some point in time (in a separate repo). For the main project it would be quite nice if we can keep it vanilla, so that it can be used with any framework and also stays small in filesize. We should however modernize it, to support NPM-packaging and stuff like that.

**Comment by JafarAkhondali** [comment]
@stevenaanen Setting max-width and ellipsis done, there were a problem with node-sass in gulp for me and have been fixed.
You are right about react :+1:

**Comment by JafarAkhondali** [comment]
@stevenaanen Did you check the PR?

**Comment by stevenaanen** [comment]
@JafarAkhondali could you explain to me what you did to fix node-sass on your machine? I'm trying to test your changes but run into the same issue. Maybe we need to update some dependencies for newer versions of node?

**Comment by JafarAkhondali** [comment]
Sure, I've just downgraded node version virtually using `n`. Looks like it's only work on old node version?! 
Here is the fix [i used](https://github.com/sass/node-sass/issues/1432#issuecomment-209661374):

```
sudo npm install -g n
sudo n 0.12.7
sudo npm install node-sass@2
sudo npm -g install node-gyp@3
sudo npm rebuild node-sass 
```

**Comment by stevenaanen** [comment]
That's also a workaround of course, hehe. Thanks for the contribution @JafarAkhondali!

**Comment by YonathanB** [comment]
Is the plugin support RTL?

**Pull request merged**
